spring:
  profiles:
    active: local
  datasource:
    url: jdbc:mysql://localhost:3306/mental_health_assistant?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      base-url: https://api.openai.com
      chat:
        model: gpt-5.6-terra
        tool-choice: auto


# Server port
server:
  port: 1236

# JWT
jwt:
  secret: MySecretKeyForJWT2025!@#$%^&*()_+SecureKeyHere # avoid to be encoded in the client side
  expiration: 86400000  # 24horse（ms）
  refresh-expiration: 604800000  # 7 days（ms）
  header: Authorization  # token header
  token-prefix: "Bearer "  # token prefix